# Name: GuessGame.py
# Author: Triumph Ogbonnia 
# Created: 11/23/30
# Description: A simple guessing game where the user has to guess a number between 1 and 20, which is randomly generated by the

import sys
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QPushButton, QVBoxLayout, QMessageBox
import random

class NumberGuessingGame(QWidget):
    def __init__(self):
        super().__init__()
        self.lower_limit = 1
        self.upper_limit = 100
        self.target_number = random.randint(self.lower_limit, self.upper_limit)
        self.attempts = 0

        self.initUI()

    def initUI(self):
        self.setWindowTitle('Number Guessing Game')
        self.setGeometry(100, 100, 400, 200)

        self.message_label = QLabel('Guess the number between {} and {}:'.format(self.lower_limit, self.upper_limit))
        self.input_box = QLineEdit(self)
        self.guess_button = QPushButton('Guess', self)
        self.play_again_button = QPushButton('Play Again', self)
        self.play_again_button.setEnabled(False)

        layout = QVBoxLayout()
        layout.addWidget(self.message_label)
        layout.addWidget(self.input_box)
        layout.addWidget(self.guess_button)
        layout.addWidget(self.play_again_button)

        self.guess_button.clicked.connect(self.make_guess)
        self.play_again_button.clicked.connect(self.play_again)

        self.setLayout(layout)

    def make_guess(self):
        try:
            user_guess = int(self.input_box.text())
        except ValueError:
            self.show_error('Please enter a valid number.')
            return

        self.attempts += 1

        if user_guess == self.target_number:
            self.show_message('Congratulations! You guessed the number {} in {} attempts.'.format(self.target_number, self.attempts))
            self.play_again_button.setEnabled(True)
        elif user_guess < self.target_number:
            self.show_message('Too low! Try again.')
        else:
            self.show_message('Too high! Try again.')

    def play_again(self):
        self.target_number = random.randint(self.lower_limit, self.upper_limit)
        self.attempts = 0
        self.input_box.clear()
        self.message_label.setText('Guess the number between {} and {}:'.format(self.lower_limit, self.upper_limit))
        self.play_again_button.setEnabled(False)

    def show_message(self, message):
        QMessageBox.information(self, 'Number Guessing Game', message)

    def show_error(self, message):
        QMessageBox.critical(self, 'Error', message)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    game = NumberGuessingGame()
    game.show()
    sys.exit(app.exec_())
